### ISSUE TITLE
Source OpenNos.Master.Server "Console" Error

### ISSUE THREAD

**Issue by Volagal258** [KILL009/Kint-Sources#77]
![Capture](https://user-images.githubusercontent.com/49163651/55344800-9e656a80-54ae-11e9-833f-b15846a0f2a8.PNG)

**Comment by KILL009** [comment]
this error is for you run in debug emulator work only on relase

**Comment by Volagal258** [comment]
I must be in What's Debug?

**Comment by KILL009** [comment]
YES BUT NO HAVE TIME

**Comment by KILL009** [comment]
yes only work on relase mode

**Comment by Volagal258** [comment]
down I'm going to relase it it should work :)

**Comment by Volagal258** [comment]
I still have the same problem :(

**Comment by Volagal258** [comment]
I will wait for an update of your departure I hope it will be done soon :)

**Comment by Volagal258** [comment]
![Capture](https://user-images.githubusercontent.com/49163651/55982594-873a3000-5c99-11e9-99eb-1625e964d41e.PNG)

**Comment by Volagal258** [comment]
same problem in Release

**Comment by EmilioTXZ** [comment]
Open me a discord private message ꧁•†•๖̶̶̶ζ͜͡ZroFreaksツ•ᴳᵒᵈ•†•꧂#2181

**Comment by Volagal258** [comment]
hello, only you can add me cars you have to block the request of friend me know Volagal # 0479 Attention I am French but I translate the sentences in English!
