### ISSUE TITLE
Eroor

### ISSUE THREAD

**Issue by H4ckerSc0rpi0n** [KILL009/Kint-Sources#78]

**Comment by H4ckerSc0rpi0n** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'SCS' does not exist in the namespace 'OpenNos' (are you missing an assembly reference?)	OpenNos.Master.Server	C:\Users\Nostale\Desktop\Kint-Sources-master\Kint-Sources-master\Kint-Sources-master\OpenNos.Master.Server\MSManager.cs	18	Active

**Comment by EmilioTXZ** [comment]
Descompress in C: https://mega.nz/#!r8lyRQjA!ODoFsM6iPbMOFfFM2NkltBrbs0XpGvjf3FNtrGjiAFQ
