### ISSUE TITLE
Error Console Login :(

### ISSUE THREAD

**Issue by Drixize** [KILL009/Kint-Sources#81]
![Capture](https://user-images.githubusercontent.com/34395869/56323353-dede0d00-616b-11e9-9625-7ab8f00f7a75.PNG)

**Comment by EmilioTXZ** [comment]
i go to fix, wait

**Comment by EmilioTXZ** [comment]
Now is fixed

**Comment by Volagal258** [comment]
Hello, here I reopen support Cars I have another problem since the update:
![Capture](https://user-images.githubusercontent.com/49163651/56865266-4b5ad680-69cc-11e9-9d26-06a2a8fa5a46.PNG)
