### ISSUE TITLE
Error Visual Studio "source"

### ISSUE THREAD

**Issue by Volagal258** [KILL009/Kint-Sources#82]
Good evening, since the last update of the source I had problem:
![Capture](https://user-images.githubusercontent.com/49163651/56869141-f7b4b100-69fc-11e9-9d9b-ccac8d931b4f.PNG)

Do you have 1 solution where it comes from me?

**Comment by EmilioTXZ** [comment]
Install  .net framework 4.7.2

**Comment by Volagal258** [comment]
The NET Framework 4.7.2 and already installed do you have other solution?

**Comment by EmilioTXZ** [comment]
Enter here https://discord.gg/ArSb2E7

**Comment by Volagal258** [comment]
ok
