### ISSUE TITLE
Issue with "PacketFactory.Initialize<WalkPacket>();" 

### ISSUE THREAD

**Issue by joaoderocha** [KILL009/Kint-Sources#84]
![Untitled](https://user-images.githubusercontent.com/30629033/57092730-6c7c3980-6ce2-11e9-9134-c8683758ec7b.png)
![Untitled2](https://user-images.githubusercontent.com/30629033/57092731-6c7c3980-6ce2-11e9-9482-a40aeff017b9.png)

even though i already have .NET sdk 4.7.2 still getting same error.

**Comment by KILL009** [comment]
I won't do anything again is this source yes

**Comment by KILL009** [comment]
you'll have to repair the mistakes
